# Site settings
title: ArtificialGoal
email: ismetcsahin@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" 
url: "https://ismetcsahin.github.io/" 

linkedin_username: ismetcsahin
username_medium: ismetcansahin
github_username: ismetcsahin

# Build settings
markdown: kramdown
